# **Quiz 1 - Python NumPy**

In [1]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


## **1. *FizzBuzz*  - Python**

---

###**Problem Description**

**Task:** Given an integer $x$ return:
 

*   The string "**`Fizz!`**" if $x$ is divisible by $3$ and not  divisible by $5$.
*    The string "**`Buzz!`**" if $x$ is divisible by $5$ and not  divisible by $3$.
*    The string "**`FizzBuzz!`**" if $x$ is divisible by both $5$ and divisible by $3$.
*    The string "**`...`**" otherwise.

**Input Format:** The input consists of a single integer $x$. 

**Constraints:** $x$ is an integer

**Output Format:**  the output is a string.

**Solution**

In [2]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
    answer =""
    # Condition 1
    if (x%3 == 0 and x%5 != 0):
      answer += "Fizz!"

    # Condition 2
    elif (x%3 != 0 and x%5 == 0):
      answer += "Buzz!"

    # Condition 3
    elif (x%3 == 0 and x%5 == 0):
      answer += "FizzBuzz!"

    else:
      answer += "..."

    return answer


In [3]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


## **2. *FizzBuzzList*  - Python**
---

Write the function *FizzBuzzList* that returns a list with the answers of *FizzBuzz* for the integer numbers $1$ to $n$ (including $n$).

---

###**Problem Description**

**Task:** Given an integer $n$ return the list with the *FizzBuzz* answers for the integer numbers $1$ to $n$ (including $n$).
  

**Input Format:** The input consists of a single integer $n$. 

**Constraints:** $n$ is an integer

**Output Format:**  list with the *FizzBuzz* answers, if the input is not positive return an empty list.

In [4]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    ans = []
    for i in range(1, n+1):
      ans.append(FizzBuzz(i))

    return ans

In [5]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


## **3. *Standarize* - z scores - NumPy**

In [6]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())

3.5749999999999997
1.6130328576938535


---

###**Problem Description**

**Task:** Given an numpy array $X$ return the corresponding standard scores.
  
**Input Format:** The input consists of a numpy array $X$. 

**Output Format:**  A numpy array with standard scores corresponding to $X$.

In [7]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = (X-X.mean())/X.std()
  return X_standarized

## **4. *Main diagonal matrix*  - NumPy**

In [8]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))

print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


---

###**Problem Description**

**Task:** Given a numpy matrix $A$ (2-D array) return the diagonal matrix with the elements of its main diagonal.
 

**Input Format:** The input consists of a numpy matrix $A$ (2-D array).

**Output Format:**  The diagonal matrix with the elemnts of its main diagonal.

In [9]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float)
  return D